
import { LanguageCode, LanguageOption, AppLanguage, UITranslation } from './types';

// NOTE: The API key tries to load from the environment variable "groq_api".
export const GROQ_API_KEY = process.env.groq_api || "";
export const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: LanguageCode.Chinese, label: '中文 (繁體)', flag: '🇹🇼' },
  { code: LanguageCode.English, label: 'English', flag: '🇺🇸' },
  { code: LanguageCode.Vietnamese, label: 'Tiếng Việt', flag: '🇻🇳' },
  { code: LanguageCode.Thai, label: 'ไทย', flag: '🇹🇭' },
  { code: LanguageCode.Indonesian, label: 'Bahasa Indonesia', flag: '🇮🇩' },
];

export const APP_LANGUAGES: { code: AppLanguage; label: string }[] = [
  { code: 'zh-TW', label: '繁體中文' },
  { code: 'en-US', label: 'English' },
  { code: 'vi-VN', label: 'Tiếng Việt' },
  { code: 'th-TH', label: 'ไทย' },
  { code: 'id-ID', label: 'Bahasa Indonesia' },
];

export const DEFAULT_SOURCE_LANG = LanguageCode.Chinese;
export const DEFAULT_TARGET_LANG = LanguageCode.Indonesian;

export const UI_TRANSLATIONS: Record<AppLanguage, UITranslation> = {
  'zh-TW': {
    appName: '2-Talk',
    settings: '設定',
    translationSettings: '1. 翻譯語言',
    headphoneSettings: '2. 耳機設定',
    volumeSettings: '3. 聲音設定',
    versionSettings: '4. 版本設定',
    languagePref: '選擇翻譯語言',
    checkLeAudio: '檢查 LE Audio 支援',
    checking: '檢查中...',
    leSupported: '已連接 LE Audio 設備',
    leNotSupported: '未檢測到支援設備',
    leDescription: '已啟用立體聲分離功能。',
    appLanguage: '介面語言版本',
    hint: '提示：點擊下方的麥克風圖示開始說話。再次點擊將停止錄音並儲存翻譯結果。',
    clearHistory: '清除所有紀錄',
    listening: '正在聆聽...',
    processing: '處理中...',
    liveTranslation: '即時翻譯',
    startRecord: '點擊翻譯',
    stopRecord: '停止',
    confirmClear: '確定要清除所有翻譯紀錄嗎？',
    rightEar: '右耳',
    leftEar: '左耳',
    enablePlayback: '啟用語音播放',
    continuousMode: '連續翻譯',
    sourceTextLabel: '原文',
    translatedTextLabel: '譯文',
    modelSettings: '5. 語音辨識模型',
    selectModel: '選擇模型',
  },
  'en-US': {
    appName: '2-Talk',
    settings: 'Settings',
    translationSettings: '1. Translation Languages',
    headphoneSettings: '2. Headphone Settings',
    volumeSettings: '3. Volume Settings',
    versionSettings: '4. Version Settings',
    languagePref: 'Select Languages',
    checkLeAudio: 'Check LE Audio',
    checking: 'Checking...',
    leSupported: 'LE Audio Device Connected',
    leNotSupported: 'No Supported Device',
    leDescription: 'Stereo separation enabled.',
    appLanguage: 'App Interface Language',
    hint: 'Hint: Tap the microphone to start speaking. Tap again to stop and save.',
    clearHistory: 'Clear History',
    listening: 'Listening...',
    processing: 'Processing...',
    liveTranslation: 'Live Translation',
    startRecord: 'Tap to start speaking',
    stopRecord: 'Stop',
    confirmClear: 'Are you sure you want to clear all history?',
    rightEar: 'Right Ear',
    leftEar: 'Left Ear',
    enablePlayback: 'Enable Playback',
    continuousMode: 'Continuous Mode',
    sourceTextLabel: 'Original',
    translatedTextLabel: 'Translation',
    modelSettings: '5. Speech Recognition Model',
    selectModel: 'Select Model',
  },
  'vi-VN': {
    appName: '2-Talk',
    settings: 'Cài đặt',
    translationSettings: '1. Ngôn ngữ dịch',
    headphoneSettings: '2. Cài đặt tai nghe',
    volumeSettings: '3. Cài đặt âm lượng',
    versionSettings: '4. Cài đặt phiên bản',
    languagePref: 'Chọn ngôn ngữ',
    checkLeAudio: 'Kiểm tra LE Audio',
    checking: 'Đang kiểm tra...',
    leSupported: 'Đã kết nối thiết bị LE Audio',
    leNotSupported: 'Không hỗ trợ thiết bị',
    leDescription: 'Đã bật tách âm thanh nổi.',
    appLanguage: 'Ngôn ngữ ứng dụng',
    hint: 'Gợi ý: Nhấn vào micro để bắt đầu nói. Nhấn lại để dừng và lưu.',
    clearHistory: 'Xóa lịch sử',
    listening: 'Đang nghe...',
    processing: 'Đang xử lý...',
    liveTranslation: 'Dịch trực tiếp',
    startRecord: 'Nhấn để nói',
    stopRecord: 'Dừng',
    confirmClear: 'Bạn có chắc chắn muốn xóa tất cả lịch sử không?',
    rightEar: 'Tai phải',
    leftEar: 'Tai trái',
    enablePlayback: 'Bật phát lại',
    continuousMode: 'Chế độ liên tục',
    sourceTextLabel: 'Bản gốc',
    translatedTextLabel: 'Bản dịch',
    modelSettings: '5. Mô hình nhận dạng giọng nói',
    selectModel: 'Chọn mô hình',
  },
  'th-TH': {
    appName: '2-Talk',
    settings: 'การตั้งค่า',
    translationSettings: '1. ภาษาแปล',
    headphoneSettings: '2. การตั้งค่าหูฟัง',
    volumeSettings: '3. การตั้งค่าระดับเสียง',
    versionSettings: '4. การตั้งค่ารุ่น',
    languagePref: 'เลือกภาษา',
    checkLeAudio: 'ตรวจสอบ LE Audio',
    checking: 'กำลังตรวจสอบ...',
    leSupported: 'เชื่อมต่ออุปกรณ์ LE Audio แล้ว',
    leNotSupported: 'ไม่พบอุปกรณ์ที่รองรับ',
    leDescription: 'เปิดใช้งานแยกเสียงสเตอริโอ',
    appLanguage: 'ภาษาแอปพลิเคชัน',
    hint: 'คำแนะนำ: แตะไมโครโฟนเพื่อเริ่มพูด แตะอีกครั้งเพื่อหยุดและบันทึก',
    clearHistory: 'ล้างประวัติ',
    listening: 'กำลังฟัง...',
    processing: 'กำลังประมวลผล...',
    liveTranslation: 'การแปลสด',
    startRecord: 'แตะเพื่อเริ่มพูด',
    stopRecord: 'หยุด',
    confirmClear: 'คุณแน่ใจหรือไม่ว่าต้องการล้างประวัติทั้งหมด?',
    rightEar: 'หูขวา',
    leftEar: 'หูซ้าย',
    enablePlayback: 'เปิดใช้งานการเล่น',
    continuousMode: 'โหมดต่อเนื่อง',
    sourceTextLabel: 'ต้นฉบับ',
    translatedTextLabel: 'คำแปล',
    modelSettings: '5. โมเดลการรู้จำเสียง',
    selectModel: 'เลือกโมเดล',
  },
  'id-ID': {
    appName: '2-Talk',
    settings: 'Pengaturan',
    translationSettings: '1. Bahasa Terjemahan',
    headphoneSettings: '2. Pengaturan Headphone',
    volumeSettings: '3. Pengaturan Volume',
    versionSettings: '4. Pengaturan Versi',
    languagePref: 'Pilih Bahasa',
    checkLeAudio: 'Periksa LE Audio',
    checking: 'Memeriksa...',
    leSupported: 'Perangkat LE Audio Terhubung',
    leNotSupported: 'Perangkat Tidak Didukung',
    leDescription: 'Pemisahan Stereo Diaktifkan.',
    appLanguage: 'Bahasa Aplikasi',
    hint: 'Petunjuk: Ketuk mikrofon untuk mulai berbicara. Ketuk lagi untuk berhenti dan menyimpan.',
    clearHistory: 'Hapus Riwayat',
    listening: 'Mendengarkan...',
    processing: 'Memproses...',
    liveTranslation: 'Terjemahan Langsung',
    startRecord: 'Ketuk untuk bicara',
    stopRecord: 'Berhenti',
    confirmClear: 'Apakah Anda yakin ingin menghapus semua riwayat?',
    rightEar: 'Telinga Kanan',
    leftEar: 'Telinga Kiri',
    enablePlayback: 'Aktifkan Pemutaran',
    continuousMode: 'Mode Berkelanjutan',
    sourceTextLabel: 'Asli',
    translatedTextLabel: 'Terjemahan',
    modelSettings: '5. Model Transkripsi',
    selectModel: 'Pilih Model',
  },
};

export const DEEPGRAM_API_KEY = "1086346cfb07b5b3df56a2169560ab033267cba9";

export const MODEL_OPTIONS: { value: 'groq' | 'deepgram'; label: string }[] = [
  { value: 'groq', label: 'Groq Whisper (Fast)' },
  { value: 'deepgram', label: 'Deepgram Nova-3 (Fastest)' },
];

export const CLOUDFLARE_BACKEND_URL = 'https://do-talk-backend.chencef.workers.dev';

// OCR 後端服務（HuggingFace Spaces）
// Space 網址：https://huggingface.co/spaces/chencef/dotalk-ocr
// 部署說明：將 hf_ocr_space/ 目錄內容推送至 HuggingFace Space repo
export const OCR_BACKEND_URL = 'https://chencef-dotalk-ocr.hf.space';

